heat_template_version: 2014-10-16

description: >
  Build network, admin access requirements inside an empty tenant and deploy an Application

resources:
  random:
    type: OS::Heat::RandomString
    properties:
      length: 6
      sequence: lettersdigits

  network:
    depends_on: [ random ]
    type: OS::Neutron::Net
    properties:
      admin_state_up: True
      name:
        str_replace:
          template: ctx%ress%-rand%
          params:
            "ctx%": {get_param: context}
            "ress%": "net"
            "rand%": { get_attr: [random, value] }
      shared: False

  subnet:
    type: OS::Neutron::Subnet
    depends_on: [ network ]
    properties:
      name:
        str_replace:
          template: ctx%ress%-rand%
          params:
            "ctx%": {get_param: context}
            "ress%": "subnet"
            "rand%": { get_attr: [random, value] }
      cidr: {get_param: subnet_cidr}
      network: {get_resource: network}
      allocation_pools: [{"start" : {get_param: subnet_start}, "end" : {get_param: subnet_end}}]
      dns_nameservers: {get_param: dns_nameservers}
      enable_dhcp: True
      gateway_ip: {get_param: gateway_ip}
      ip_version: 4
      host_routes:
        - destination: "0.0.0.0/0"
          nexthop: {get_param: gateway_ip}

  router:
    type: OS::Neutron::Router
    properties:
      name:
        str_replace:
          template: ctx%ress%-rand%
          params:
            "ctx%": {get_param: context}
            "ress%": "router"
            "rand%": { get_attr: [random, value] }
      admin_state_up: True
      external_gateway_info: {"network": {get_param: floatingip_network_name}}

  interface:
    type: OS::Neutron::RouterInterface
    depends_on: [ router, subnet ]
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: subnet }

  bench_securitygroup:
      depends_on: [ random ]
      type: OS::Neutron::SecurityGroup
      properties:
        name:
          str_replace:
            template: ctx%ress%-rand%
            params:
              "ctx%": {get_param: context}
              "ress%": "bench"
              "rand%": { get_attr: [random, value] }
        rules:
          - remote_ip_prefix: {get_param: subnet_cidr}
            protocol: tcp
            port_range_min: 22
            port_range_max: 22
            direction: ingress
          - remote_ip_prefix: {get_param: subnet_cidr}
            protocol: icmp
            direction: ingress

  bastion_securitygroup:
      depends_on: [ random ]
      type: OS::Neutron::SecurityGroup
      properties:
        name:
          str_replace:
            template: ctx%ress%-rand%
            params:
              "ctx%": {get_param: context}
              "ress%": "bastion"
              "rand%": { get_attr: [random, value] }
        rules:
          - remote_ip_prefix: 0.0.0.0/0
            protocol: tcp
            port_range_min: 22
            port_range_max: 22
            direction: ingress
          - remote_ip_prefix: 0.0.0.0/0
            protocol: icmp
            direction: ingress

  bastion_group:
    depends_on: [ interface, bastion_securitygroup, bastion_userdata ]
    type: OS::Heat::ResourceGroup
    properties:
      count: 0
      resource_def:
        type: "lib::FIPInstance"
        properties:
          key_name: { get_param: key_name }
          security_group: { get_resource: bastion_securitygroup }
          network: { get_resource: network }
          subnet: { get_resource: subnet }
          userdata: { get_resource: bastion_userdata }
          flavor: { get_param: flavor }
          image: { get_param: image }
          floatingip_network_name: { get_param: floatingip_network_name }
          instance_basename:
            str_replace:
              template: ctx%rand%-ress%-%index%
              params:
                "ctx%": {get_param: context}
                "ress%": "bastion"
                "rand%": { get_attr: [random, value] }

  bench_group:
    depends_on: [ interface, bench_securitygroup, bench_userdata ]
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 1
      desired_capacity: { get_param: benchmark_size }
      max_size: 20
      rolling_updates: {"max_batch_size": 1, "min_in_service": 1, "pause_time": 30}
      resource:
        type: "lib::FIPInstance"
        properties:
          key_name: { get_param: key_name }
          security_group: { get_resource: bench_securitygroup }
          network: { get_resource: network }
          subnet: { get_resource: subnet }
          userdata: { get_resource: bench_userdata }
          flavor: { get_param: flavor }
          image: { get_param: image }
          floatingip_network_name: { get_param: floatingip_network_name }
          instance_basename:
            str_replace:
             template: ctx%rand%-ress%
             params:
               "ctx%": {get_param: context}
               "rand%": { get_attr: [random, value] }
               "ress%": "bench"

  scale_up:
    depends_on: [ bench_group ]
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: bench_group}
      cooldown: 30
      scaling_adjustment: 2

  scale_down:
    depends_on: [ bench_group ]
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: bench_group}
      cooldown: 30
      scaling_adjustment: -2

  bench_userdata:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        package_update: false
        package_upgrade: false
        packages:
         - curl

        runcmd:
          - [curl, -LI, {get_param: url_benchmark}]
          - curl -L -k https://get.docker.com | sh
          - [docker, run, --rm, williamyeh/wrk, -t8, -c4000, -d300s, {get_param: url_benchmark}]


  bastion_userdata:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        package_update: true
        package_upgrade: true
        packages:
          - curl

parameters:
  url_benchmark:
    type: string

  context:
    type: string
    default: ""

  key_name:
    type: string
    label: Name of keypair to assign to servers
    description: key_name=foo

  subnet_cidr:
    type: string
    default: "192.168.1.0/24"

  subnet_start:
    type: string
    default: "192.168.1.100"

  subnet_end:
    type: string
    default: "192.168.1.200"

  gateway_ip:
    type: string
    default: "192.168.1.254"

  dns_nameservers:
    type: comma_delimited_list
    label: DNS nameservers
    description: dns_nameservers=8.8.8.8,8.8.4.4

  floatingip_network_name:
    type: string
    label: The Floating IP network for NAT
    description: floatingip_network_name=public

  flavor:
    type: string
    label: The flavor for Instances
    description: flavor=m1.medium

  image:
    type: string
    label: The debian image based for Instances
    description: image=debian-8-2016-01-01

  benchmark_size:
    type: number
    default: 2
    constraints:
      - range: { min: 1 }

outputs:
  scale_up:
    value:
      - {get_attr: [scale_up, alarm_url]}
  scale_down:
    value:
      - {get_attr: [scale_down, alarm_url]}
  base_name:
    description: Random value used to tag stack resources
    value:
      - { get_attr: [random, value] }