heat_template_version: 2014-10-16

description: >
  Build everything inside an empty tenant

resources:
  random:
    type: OS::Heat::RandomString
    properties:
      length: 6
      sequence: lettersdigits

  local_net:
    depends_on: [ random ]
    type: OS::Neutron::Net
    properties:
      admin_state_up: True
      name:
        str_replace:
          template: ctx%ress%-rand%
          params:
            "ctx%": {get_param: context}
            "ress%": "net"
            "rand%": { get_attr: [random, value] }
      shared: False

  local_sub:
    type: OS::Neutron::Subnet
    depends_on: [ local_net ]
    properties:
      name:
        str_replace:
          template: ctx%ress%-rand%
          params:
            "ctx%": {get_param: context}
            "ress%": "subnet"
            "rand%": { get_attr: [random, value] }
      cidr: {get_param: local_sub_cidr}
      network: {get_resource: local_net}
      allocation_pools: [{"start" : {get_param: local_sub_start}, "end" : {get_param: local_sub_end}}]
      dns_nameservers: {get_param: dns_nameservers}
      enable_dhcp: True
      gateway_ip: {get_param: local_gateway}
      ip_version: 4

  local_router:
    type: OS::Neutron::Router
    depends_on: [ local_sub ]
    properties:
      name:
        str_replace:
          template: ctx%ress%-rand%
          params:
            "ctx%": {get_param: context}
            "ress%": "router"
            "rand%": { get_attr: [random, value] }
      admin_state_up: True
      external_gateway_info: {"network": {get_param: floatingip_network_name}}

  local_inet:
    type: OS::Neutron::RouterInterface
    depends_on: [ local_router ]
    properties:
      router_id: { get_resource: local_router }
      subnet_id: { get_resource: local_sub }

  basic_sg:
      depends_on: [ random ]
      type: OS::Neutron::SecurityGroup
      properties:
        name:
          str_replace:
            template: ctx%ress%-rand%
            params:
              "ctx%": {get_param: context}
              "ress%": "basic"
              "rand%": { get_attr: [random, value] }
        rules:
          - remote_ip_prefix: {get_param: local_sub_cidr}
            protocol: tcp
            port_range_min: 22
            port_range_max: 22
            direction: ingress
          - remote_ip_prefix: {get_param: local_sub_cidr}
            protocol: tcp
            port_range_min: 80
            port_range_max: 80
            direction: ingress
          - remote_ip_prefix: {get_param: local_sub_cidr}
            protocol: icmp
            direction: ingress

  basic_scale:
    depends_on: [ local_inet, basic_sg, basic_userdata ]
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 2
      max_size: 6
      rolling_updates: {"max_batch_size": 1, "min_in_service": 2, "pause_time": 60}
      resource:
        type: OS::Nova::Server
        properties:
          key_name: { get_param: key_name }
          image: { get_param: image }
          flavor: { get_param: flavor }
          networks:
            - network: {get_resource: local_net}
          user_data_format: RAW
          user_data: { get_resource: basic_userdata }

  scale_up:
    depends_on: [ basic_scale ]
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: basic_scale}
      cooldown: 30
      scaling_adjustment: 1

  scale_down:
    depends_on: [ basic_scale ]
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: basic_scale}
      cooldown: 30
      scaling_adjustment: -1

  basic_userdata:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        runcmd:
          - [ echo, "hello_world" ]

parameters:
  context:
    type: string
    default: ""
  key_name:
    type: string
    label: Name of keypair to assign to servers
    description: key_name=foo
  local_sub_cidr:
    type: string
    default: "192.168.1.0/24"
  local_sub_start:
    type: string
    default: "192.168.1.100"
  local_sub_end:
    type: string
    default: "192.168.1.200"
  local_gateway:
    type: string
    default: "192.168.1.254"
  dns_nameservers:
    type: comma_delimited_list
    label: DNS nameservers
    description: dns_nameservers=8.8.8.8,8.8.4.4
  floatingip_network_name:
    type: string
    label: The Floating IP network for NAT
    description: floatingip_network_name=public
  flavor:
    type: string
    label: The flavor for Instances
    description: flavor=m1.medium
  image:
    type: string
    label: The debian image based for Instances
    description: image=debian-8-2016-01-01

outputs:
  scale_up:
    value:
      - {get_attr: [scale_up, alarm_url]}
  scale_down:
    value:
      - {get_attr: [scale_down, alarm_url]}
  base_name:
    description: Random value used to tag stack resources
    value:
      - { get_attr: [random, value] }