heat_template_version: 2014-10-16

description: >
  Instance with UserData

resources:
  random:
    type: OS::Heat::RandomString
    properties:
      length: 10
      sequence: lettersdigits

  floating:
    type: OS::Neutron::FloatingIP
    depends_on: [ port ]
    properties:
      floating_network: { get_param: floatingip_network_name }
      port_id: { get_resource: port }

  port:
    depends_on: [ random ]
    type: OS::Neutron::Port
    properties:
      name:
        str_replace:
          template: bn%-rand%
          params:
            "bn%": { get_param: instance_basename }
            "rand%": { get_attr: [random, value] }
      network_id: { get_param: network }
      fixed_ips:
        - subnet_id: { get_param: subnet }
      security_groups: [ { get_param: security_group } ]

  instance:
    depends_on: [ port, etcd_userdata ]
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: bn%-rand%
          params:
            "bn%": { get_param: instance_basename }
            "rand%": { get_attr: [random, value] }
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: port }
      user_data_format: RAW
      user_data: { get_resource: etcd_userdata }
      scheduler_hints:
        group: { get_param: anti_affinity }

  etcd_userdata:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        write_files:
          - path: /lib/systemd/system/etcd.service
            permissions: 0644
            content:
              str_replace:
                params:
                  __prefix__: { get_param: prefix }
                template: |
                  [Unit]
                  Description=etcd2
                  Conflicts=etcd.service

                  [Service]
                  Type=notify
                  ExecStart=/usr/bin/etcd \
                    -proxy on \
                    -data-dir /var/lib/etcd2 \
                    -listen-client-urls http://0.0.0.0:8080 \
                    -initial-cluster static0=http://__prefix__0:2380,static1=http://__prefix__1:2380,static2=http://__prefix__2:2380
                  Restart=always
                  RestartSec=10s
                  LimitNOFILE=40000
                  TimeoutStartSec=0

                  [Install]
                  WantedBy=multi-user.target
          - path: /tmp/nginx_etcd_proxy
            permissions: 0644
            content:
              str_replace:
                params:
                  __instance_basename__:
                    str_replace:
                      template: bn%-rand%
                      params:
                        "bn%": { get_param: instance_basename }
                        "rand%": { get_attr: [random, value] }
                template: |
                  server {
                          listen   80;
                          server_name     __instance_basename__;
                          location / {
                                  proxy_pass         http://127.0.0.1:8080/;

                          }
                  }
        runcmd:
          - set -x
          - apt-get update
          #- apt-get upgrade -y
          - apt-get install -y curl jq nginx
          - mkdir /tmp/etcd_install || rm -Rf /tmp/etcd_install/*
          - [curl, -L, {get_param: insecure}, {get_param: etcd_tar}, -o, /tmp/etcd_install/etcd.tar.gz]
          - cd -P /tmp/etcd_install
          - tar -xzvf /tmp/etcd_install/etcd.tar.gz --strip-components=1
          - mv /tmp/etcd_install/etcd /usr/bin/etcd
          - mv /tmp/etcd_install/etcdctl /usr/bin/etcdctl
          - mkdir -p /var/lib/etcd2
          - mv /tmp/nginx_etcd_proxy /etc/nginx/sites-available/default
          - service nginx reload && echo $?
          - systemctl daemon-reload
          - systemctl enable etcd.service
          - systemctl start etcd.service
          - systemctl status etcd.service


parameters:
  instance_basename:
    type: string
  key_name:
    type: string
  security_group:
    type: string
  network:
    type: string
  subnet:
    type: string
  image:
    type: string
  flavor:
    type: string
  insecure:
    type: string
  etcd_tar:
    type: string
  prefix:
    type: string
  anti_affinity:
    type: string
  floatingip_network_name:
    type: string