heat_template_version: 2014-10-16

description: >
  Discovery nested stack to build with AutoScalingGroup or ResourceGroup

resources:
  random:
    type: OS::Heat::RandomString
    properties:
      length: 12
      sequence: lettersdigits

  port:
    depends_on: [ random ]
    type: OS::Neutron::Port
    properties:
      name:
        str_replace:
          template: bn%-rand%
          params:
            "bn%": { get_param: instance_basename }
            "rand%": { get_attr: [random, value] }
      network_id: { get_param: network }
      fixed_ips:
        - subnet_id: { get_param: subnet }
      security_groups: [ { get_param: security_group } ]

  instance:
    depends_on: [ port, etcd_userdata ]
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: bn%-rand%
          params:
            "bn%": { get_param: instance_basename }
            "rand%": { get_attr: [random, value] }
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: port }
      user_data_format: RAW
      user_data: { get_resource: etcd_userdata }
      scheduler_hints:
        group: { get_param: anti_affinity }

  etcd_userdata:
    depends_on: [ port ]
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        package_update: true
        package_upgrade: false
        packages:
         - curl
         - jq
         - tar
        write_files:
          - path: /lib/systemd/system/etcd-proxy-static.service
            permissions: 0644
            content:
              str_replace:
                params:
                  __static_endpoint__: { get_param: static_endpoint }
                  __instance_basename__:
                    str_replace:
                      template: bn%-rand%
                      params:
                        "bn%": { get_param: instance_basename }
                        "rand%": { get_attr: [random, value] }
                template: |
                  [Unit]
                  Description=etcd2 static proxy
                  Conflicts=etcd-proxy-static.service

                  [Service]
                  Type=idle
                  ExecStart=/usr/bin/etcd \
                    -name __instance_basename__ \
                    -proxy on \
                    -data-dir /var/lib/etcd2_proxy_static \
                    -listen-client-urls http://127.0.0.1:8081 \
                    -initial-cluster __static_endpoint__
                  Restart=always
                  RestartSec=10s
                  LimitNOFILE=40000
                  TimeoutStartSec=0

                  [Install]
                  WantedBy=multi-user.target
          - path: /lib/systemd/system/etcd.service
            permissions: 0644
            content:
              str_replace:
                params:
                  __token__: { get_param: token }
                  __ip_address__: { get_attr: [port, fixed_ips, 0, ip_address] }
                  __instance_basename__:
                    str_replace:
                      template: bn%-rand%
                      params:
                        "bn%": { get_param: instance_basename }
                        "rand%": { get_attr: [random, value] }
                template: |
                  [Unit]
                  Description=etcd2
                  Conflicts=etcd.service
                  Requires=etcd-proxy-static.service

                  [Service]
                  Type=notify
                  ExecStart=/usr/bin/etcd \
                    -name __instance_basename__ \
                    -data-dir /var/lib/etcd2 \
                    -initial-advertise-peer-urls http://__ip_address__:2380 \
                    -listen-peer-urls http://__ip_address__:2380 \
                    -listen-client-urls http://__ip_address__:2379,http://127.0.0.1:2379 \
                    -advertise-client-urls http://__ip_address__:2379 \
                    -discovery http://localhost:8081/v2/keys/discovery/__token__
                  Restart=always
                  RestartSec=10s
                  LimitNOFILE=40000
                  TimeoutStartSec=0

                  [Install]
                  WantedBy=multi-user.target
          - path: /etc/etcd_waiting
            permissions: 0544
            content:
              str_replace:
                params:
                  __default_target__: { get_param: static_proxy_bind }
                template: |
                  #! /bin/bash

                  TARGET=$1
                  DEFAULT_TARGET=__default_target__
                  UPSERT=?prevExist=false
                  SLEEP=10

                  function check_param
                  {
                      if [ $# -ne 1 ]
                      then
                          echo "1 parameter expected TARGET: [$#] given"
                          TARGET=${DEFAULT_TARGET}
                      fi
                  }

                  function waiting_endpoint
                  {
                      for i in {0..20}
                      do
                          curl ${TARGET}
                          if [ $? -eq 0 ]
                              then
                                echo "loop ${i} -> ${TARGET} READY ret: $?"
                                return 0
                              fi
                          echo "loop ${i} -> ${TARGET} not ready ret: $?"
                          sleep ${SLEEP}
                      done
                      exit 2
                  }

                  # MAIN
                  set -x
                  check_param
                  waiting_endpoint

        runcmd:
          - set -x

          # Install from release or object store stagging
          - mkdir /tmp/etcd_install || rm -Rf /tmp/etcd_install/*
          - [curl, -L, {get_param: insecure}, {get_param: etcd_tar}, -o, /tmp/etcd_install/etcd.tar.gz]
          - cd -P /tmp/etcd_install
          - tar -xzvf /tmp/etcd_install/etcd.tar.gz --strip-components=1
          - mv /tmp/etcd_install/etcd /usr/bin/etcd
          - mv /tmp/etcd_install/etcdctl /usr/bin/etcdctl
          - mkdir -p /var/lib/etcd2 && mkdir -p /var/lib/etcd2_proxy_static

          # Capable because of write_files section
          - systemctl daemon-reload
          - systemctl enable etcd-proxy-static.service
          - systemctl start etcd-proxy-static.service && systemctl status etcd-proxy-static.service
          - systemctl enable etcd.service
          - [/etc/etcd_waiting]
          - [ curl, -XPUT, {get_param: create_discovery}, -d, {get_param: value_etcd_size} ]
          - systemctl start etcd.service && systemctl status etcd.service


parameters:
  instance_basename:
    type: string

  key_name:
    type: string

  security_group:
    type: string

  network:
    type: string

  subnet:
    type: string

  image:
    type: string

  flavor:
    type: string

  insecure:
    type: string

  etcd_tar:
    type: string

  create_discovery:
    type: string

  value_etcd_size:
    type: string

  anti_affinity:
    type: string

  static_endpoint:
    type: string

  token:
    type: string

  static_proxy_bind:
    type: string
    default: "http://127.0.0.1:8081"