heat_template_version: 2014-10-16

description: >
  Build network, admin access requirements inside an empty tenant and deploy an Application

resources:
  random:
    type: OS::Heat::RandomString
    properties:
      length: 6
      sequence: lettersdigits

  network:
    depends_on: [ random ]
    type: OS::Neutron::Net
    properties:
      admin_state_up: True
      name:
        str_replace:
          template: ctx%ress%-rand%
          params:
            "ctx%": {get_param: context}
            "ress%": "net"
            "rand%": { get_attr: [random, value] }
      shared: False

  subnet:
    type: OS::Neutron::Subnet
    depends_on: [ network ]
    properties:
      name:
        str_replace:
          template: ctx%ress%-rand%
          params:
            "ctx%": {get_param: context}
            "ress%": "subnet"
            "rand%": { get_attr: [random, value] }
      cidr: {get_param: subnet_cidr}
      network: {get_resource: network}
      allocation_pools: [{"start" : {get_param: subnet_start}, "end" : {get_param: subnet_end}}]
      dns_nameservers: {get_param: dns_nameservers}
      enable_dhcp: True
      gateway_ip: {get_param: gateway_ip}
      ip_version: 4

  router:
    type: OS::Neutron::Router
    depends_on: [ subnet ]
    properties:
      name:
        str_replace:
          template: ctx%ress%-rand%
          params:
            "ctx%": {get_param: context}
            "ress%": "router"
            "rand%": { get_attr: [random, value] }
      admin_state_up: True
      external_gateway_info: {"network": {get_param: floatingip_network_name}}

  interface:
    type: OS::Neutron::RouterInterface
    depends_on: [ router ]
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: subnet }

  jenkins_securitygroup:
      depends_on: [ random ]
      type: OS::Neutron::SecurityGroup
      properties:
        name:
          str_replace:
            template: ctx%ress%-rand%
            params:
              "ctx%": {get_param: context}
              "ress%": "jenkins"
              "rand%": { get_attr: [random, value] }
        rules:
          - remote_ip_prefix: {get_param: subnet_cidr}
            protocol: tcp
            port_range_min: 22
            port_range_max: 22
            direction: ingress
          - remote_ip_prefix: 0.0.0.0/0
            protocol: tcp
            port_range_min: 80
            port_range_max: 80
            direction: ingress
          - remote_ip_prefix: 0.0.0.0/0
            protocol: icmp
            direction: ingress

  slaves_securitygroup:
      depends_on: [ random ]
      type: OS::Neutron::SecurityGroup
      properties:
        name:
          str_replace:
            template: ctx%ress%-rand%
            params:
              "ctx%": {get_param: context}
              "ress%": "slaves"
              "rand%": { get_attr: [random, value] }
        rules:
          - remote_ip_prefix: {get_param: subnet_cidr}
            protocol: tcp
            port_range_min: 22
            port_range_max: 22
            direction: ingress
          - remote_ip_prefix: {get_param: subnet_cidr}
            protocol: icmp
            direction: ingress

  bastion_securitygroup:
      depends_on: [ random ]
      type: OS::Neutron::SecurityGroup
      properties:
        name:
          str_replace:
            template: ctx%ress%-rand%
            params:
              "ctx%": {get_param: context}
              "ress%": "bastion"
              "rand%": { get_attr: [random, value] }
        rules:
          - remote_ip_prefix: 0.0.0.0/0
            protocol: tcp
            port_range_min: 22
            port_range_max: 22
            direction: ingress
          - remote_ip_prefix: 0.0.0.0/0
            protocol: icmp
            direction: ingress

  bastion_group:
    depends_on: [ interface, bastion_securitygroup, bastion_userdata ]
    type: OS::Heat::ResourceGroup
    properties:
      count: 1
      resource_def:
        type: "lib::FIPInstance"
        properties:
          key_name: { get_param: key_name }
          security_group: { get_resource: bastion_securitygroup }
          network: { get_resource: network }
          subnet: { get_resource: subnet }
          userdata: { get_resource: bastion_userdata }
          flavor: { get_param: flavor }
          image: { get_param: image }
          floatingip_network_name: { get_param: floatingip_network_name }
          instance_basename:
            str_replace:
              template: ctx%rand%-ress%-%index%
              params:
                "ctx%": {get_param: context}
                "ress%": "bastion"
                "rand%": { get_attr: [random, value] }

  slaves_group:
    depends_on: [ interface, slaves_securitygroup, slaves_userdata ]
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 0
      desired_capacity: 0
      max_size: 3
      rolling_updates: {"max_batch_size": 1, "min_in_service": 0, "pause_time": 60}
      resource:
        type: "lib::BaseInstance"
        properties:
          key_name: { get_param: key_name }
          security_group: { get_resource: slaves_securitygroup }
          network: { get_resource: network }
          subnet: { get_resource: subnet }
          userdata: { get_resource: slaves_userdata }
          flavor: { get_param: flavor }
          image: { get_param: image }
          instance_basename:
            str_replace:
             template: ctx%rand%-ress%
             params:
               "ctx%": {get_param: context}
               "rand%": { get_attr: [random, value] }
               "ress%": "slaves"

  jenkins_group:
    depends_on: [ interface, jenkins_securitygroup, jenkins_userdata, slaves_group ]
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 1
      desired_capacity: 1
      max_size: 3
      resource:
        type: "lib::FIPInstance"
        properties:
          key_name: { get_param: key_name }
          security_group: { get_resource: jenkins_securitygroup }
          network: { get_resource: network }
          subnet: { get_resource: subnet }
          userdata: { get_resource: jenkins_userdata }
          flavor: { get_param: flavor }
          image: { get_param: image }
          floatingip_network_name: { get_param: floatingip_network_name }
          instance_basename:
            str_replace:
             template: ctx%rand%-ress%
             params:
               "ctx%": {get_param: context}
               "rand%": { get_attr: [random, value] }
               "ress%": "jenkins"

  scale_up:
    depends_on: [ slaves_group ]
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: slaves_group}
      cooldown: 30
      scaling_adjustment: 1

  scale_down:
    depends_on: [ slaves_group ]
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: slaves_group}
      cooldown: 30
      scaling_adjustment: -1

  slaves_userdata:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        runcmd:
          - [ echo, "START" ]
          - [ echo, "hello_world" ]
          - [ echo, "END" ]

  jenkins_userdata:
    depends_on: [ slaves_group ]
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        runcmd:
          - [ echo, "START" ]
          - apt-get update -qq
          - apt-get upgrade -y
          - apt-get install openjdk-8-jre-headless daemon psmisc -y
          - [curl, { get_param: insecure}, { get_param: jenkins_deb}, -o, /tmp/jenkins.deb]
          - dpkg -i /tmp/jenkins.deb
          - apt-get install nginx -y
          - mkdir -p /var/log/nginx/jenkins
          - [curl, { get_param: insecure}, { get_param: nginx_jenkins}, -o, /etc/nginx/sites-available/default]
          - service nginx reload
          - [ echo, "END" ]

  bastion_userdata:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        runcmd:
          - [ echo, "hello_world" ]

  reverseproxy_userdata:
    depends_on: [ jenkins_group ]
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        runcmd:
          - [ echo, "START" ]
          - apt-get update
          - apt-get install -y nginx

parameters:
  key_name:
    type: string
  context:
    type: string
    default: ""
  subnet_cidr:
    type: string
    default: "192.168.1.0/24"
  subnet_start:
    type: string
    default: "192.168.1.100"
  subnet_end:
    type: string
    default: "192.168.1.200"
  gateway_ip:
    type: string
    default: "192.168.1.254"
  dns_nameservers:
    type: comma_delimited_list
    label: DNS nameservers
    description: dns_nameservers=8.8.8.8,8.8.4.4
  floatingip_network_name:
    type: string
    label: The Floating IP network for NAT
    description: floatingip_network_name=public
  flavor:
    type: string
    label: The flavor for Instances
    description: flavor=m1.medium
  image:
    type: string
    label: The debian image based for Instances
    description: image=debian-8-2016-01-01
  jenkins_deb:
    type: string
    label: The url where jenkins deb is store
  nginx_jenkins:
    type: string
    label: The url where jenkins deb is store
  insecure:
    type: string
    default: "--insecure"


outputs:
  scale_up:
    value:
      - {get_attr: [scale_up, alarm_url]}
  scale_down:
    value:
      - {get_attr: [scale_down, alarm_url]}
  base_name:
    description: Random value used to tag stack resources
    value:
      - { get_attr: [random, value] }