heat_template_version: 2014-10-16

description: >
  Build discovery etcd2 cluster over given discovery url

resources:
  random:
    type: OS::Heat::RandomString
    properties:
      length: 4
      sequence: lettersdigits

  etcd_network:
    depends_on: [ random ]
    type: OS::Neutron::Net
    properties:
      admin_state_up: True
      name:
        str_replace:
          template: ctx%rand%-ress%
          params:
            "ctx%": {get_param: context}
            "ress%": "etcd_net"
            "rand%": { get_attr: [random, value] }
      shared: False

  etcd_subnet:
    type: OS::Neutron::Subnet
    depends_on: [ etcd_network ]
    properties:
      name:
        str_replace:
          template: ctx%rand%-ress%
          params:
            "ctx%": {get_param: context}
            "ress%": "etcd_subnet"
            "rand%": { get_attr: [random, value] }
      cidr: {get_param: etcd_subnet_cidr}
      network: {get_resource: etcd_network}
      allocation_pools: [{"start" : {get_param: etcd_subnet_start}, "end" : {get_param: etcd_subnet_end}}]
      dns_nameservers: {get_param: dns_nameservers}
      enable_dhcp: True
      gateway_ip: {get_param: etcd_gateway_ip}
      ip_version: 4
      host_routes:
        - destination: "0.0.0.0/0"
          nexthop: {get_param: etcd_gateway_ip}

  etcd_interface:
    type: OS::Neutron::RouterInterface
    depends_on: [ etcd_subnet ]
    properties:
      router_id: { get_param: plug_to_router }
      subnet_id: { get_resource: etcd_subnet }

  etcd_securitygroup:
      depends_on: [ random ]
      type: OS::Neutron::SecurityGroup
      properties:
        name:
          str_replace:
            template: ctx%ress%-rand%
            params:
              "ctx%": {get_param: context}
              "ress%": "etcd"
              "rand%": { get_attr: [random, value] }
        rules:
          - remote_ip_prefix: {get_param: etcd_listen_cidr}
            protocol: tcp
            port_range_min: 22
            port_range_max: 22
            direction: ingress
          - remote_ip_prefix: {get_param: etcd_listen_cidr}
            protocol: tcp
            port_range_min: 2379
            port_range_max: 2380
            direction: ingress
          - remote_ip_prefix: {get_param: etcd_listen_cidr}
            protocol: icmp
            direction: ingress

  etcd_anti:
    depends_on: [ random ]
    type: OS::Nova::ServerGroup
    properties:
      name:
        str_replace:
          template: ctx%ress%-rand%
          params:
            "ctx%": {get_param: context}
            "ress%": "etcd"
            "rand%": { get_attr: [random, value] }
      policies: ["anti-affinity"] # Beware about the number of compute nodes

  etcd_group:
    depends_on: [ etcd_interface, etcd_anti, etcd_securitygroup ]
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 3
      desired_capacity: { get_param: etcd_size }
      max_size: 9
      rolling_updates: {"max_batch_size": 1, "min_in_service": 1, "pause_time": 60}
      resource:
        type: "EtcdDiscovery"
        properties:
          anti_affinity: { get_resource: etcd_anti }
          key_name: { get_param: key_name }
          security_group: { get_resource: etcd_securitygroup }
          network: { get_resource: etcd_network }
          subnet: { get_resource: etcd_subnet }
          flavor: { get_param: flavor }
          image: { get_param: image }
          instance_basename:
            str_replace:
             template: ctx%rand%-ress%
             params:
               "ctx%": {get_param: context}
               "rand%": { get_attr: [random, value] }
               "ress%": "etcd"
          insecure: {get_param: insecure}
          etcd_tar: {get_param: etcd_tar}
          etcd_discovery_url: {get_param: etcd_discovery_url}

  etcd_scale_up:
    depends_on: [ etcd_group ]
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: etcd_group}
      cooldown: 30
      scaling_adjustment: 1

  etcd_scale_down:
    depends_on: [ etcd_group ]
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: etcd_group}
      cooldown: 30
      scaling_adjustment: -1


outputs:
  base_name:
    description: Random value used to tag stack resources
    value:
      - { get_attr: [random, value] }

  etcd_scale_up:
    value:
      - {get_attr: [etcd_scale_up, alarm_url]}
  etcd_scale_down:
    value:
      - {get_attr: [etcd_scale_down, alarm_url]}



parameters:
  context:
    type: string
    default: ""

  key_name:
    type: string
    label: Name of keypair to assign to servers
    description: key_name=foo
    constraints:
      - custom_constraint: nova.keypair

  etcd_listen_cidr:
    type: string
    default: "0.0.0.0/0"
    constraints:
      - allowed_pattern: "[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}/[0-9]{1,2}"
        description: Must be a CIDR like 192.168.1.0/24

  etcd_subnet_cidr:
    type: string
    default: "192.168.10.0/24"
    constraints:
      - allowed_pattern: "[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}/[0-9]{1,2}"
        description: Must be a CIDR like 192.168.1.0/24

  etcd_subnet_start:
    type: string
    default: "192.168.10.100"
    constraints:
      - allowed_pattern: "[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}"
        description: Must be a valid IP address like 192.168.1.200

  etcd_subnet_end:
    type: string
    default: "192.168.10.200"
    constraints:
      - allowed_pattern: "[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}"
        description: Must be a valid IP address like 192.168.1.200

  etcd_gateway_ip:
    type: string
    default: "192.168.10.254"
    constraints:
      - allowed_pattern: "[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}"
        description: Must be a valid IP address like 192.168.1.200

  dns_nameservers:
    type: comma_delimited_list
    label: DNS nameservers
    description: dns_nameservers=8.8.8.8,8.8.4.4

  flavor:
    type: string
    label: The flavor for Instances
    description: flavor=m1.medium
    constraints:
      - custom_constraint: nova.flavor

  image:
    type: string
    label: The debian image based for Instances
    description: image=debian-8-2016-01-01
    constraints:
      - custom_constraint: glance.image

  etcd_tar:
    type: string
    description: "https://github.com/coreos/etcd/releases/version/arch.tar.gz"

  insecure:
    type: string
    default: "--insecure"
    description: Warning with curl command for https

  etcd_discovery_url:
    type: string

  etcd_size:
    type: number
    default: 3
    constraints:
    - type: Choice
      values:
      - 1
      - 3
      - 5
      - 9
    constraints:
      - range: { min: 1 }

  plug_to_router:
    type: string
    constraints:
    - allowed_pattern: ".{8}-.{4}-.{4}-.{4}-.{12}"
      description: Must be a router id